/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'author' : string,
  'summary' : string,
  'category' : string,
}
export interface ConsultationBooking {
  'name' : string,
  'email' : string,
  'serviceInterest' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface ContactInquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'reviewText' : string,
  'rating' : bigint,
  'location' : string,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[string, string, string, string, string], bigint>,
  'addTestimonial' : ActorMethod<[string, string, bigint, string], bigint>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllConsultationBookings' : ActorMethod<[], Array<ConsultationBooking>>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllTestimonialsHighestRating' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPostById' : ActorMethod<[bigint], BlogPost>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitInquiry' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];